import jsPDF from 'jspdf';
import { generateTrBensPdf } from './services/pdf/trBensGenerator.ts';
import { existsSync, statSync } from 'fs';

const data = {
  pae: '2025/0001',
  setor: 'DL/DAL',
  itens: [],
  justificativaAgrupamento: 'Não se aplica.',
  motivoContratacao: 'Aquisição de bens.',
  naturezaBem: 'comum',
  provaQualidade: 'nao',
  justificativaProvaQualidade: '',
  amostra: 'nao',
  amostraPrazo: '03',
  justificativaAmostra: '',
  garantiaBem: 'nao',
  garantiaBemMeses: '',
  garantiaItens: '',
  assistenciaTecnica: 'nao',
  assistenciaTecnicaItens: '',
  assistenciaTecnicaMeses: '',
  assistenciaTecnicaModo: '',
  formaContratacao: ['pregao'],
  inexigibilidadeInciso: '',
  dispensaInciso: '',
  fundamentoLegal: '',
  criterioJulgamento: 'menor_preco',
  orcamentoSigiloso: 'nao',
  justificativaOrcamentoSigiloso: '',
  criterioAceitabilidade: 'Critério de aceitabilidade.',
  participacaoME: 'sim',
  participacaoMEItens: '01, 02 e 05',
  itensParticipacaoExclusiva: '',
  itensParticipacaoExclusivaDesc: '',
  habilitacaoJuridica: [],
  habilitacaoFiscal: [],
  qualificacaoEconomica: [],
  habilitacaoTecnicaExigida: 'nao',
  habilitacaoTecnicaQual: '',
  habilitacaoTecnicaPorque: '',
  qualificacoesTecnicas: [],
  qualificacoesTecnicasJustificativas: {},
  criterioSustentabilidade: 'nao',
  criterioSustentabilidadeDesc: '',
  riscosAssumidos: 'nao',
  riscosAssumidosDesc: '',
  participacaoConsorcio: 'nao',
  participacaoConsorcioJustificativa: '',
  participacaoConsorcioPercentual: '10',
  subcontratacao: 'nao',
  subcontratacaoOpcao: '',
  subcontratacaoDetalhes: '',
  formaEntregaTipo: 'unica',
  entregaParcelasX: '',
  entregaParcelasY: '',
  entregaParcelasZ: '',
  localEntrega: 'Setor',
  prazoValidadePereciveis: '',
  prazoContrato: '30',
  possibilidadeProrrogacao: 'nao',
  pagamentoMeio: '',
  pagamentoOnde: '',
  pagamentoPrazoDias: '30',
  pagamentoRegularidade: '',
  pagamentoOpcoes: [],
  garantiaContratoTipo: 'nao_ha',
  garantiaContratoPorcentagem: '',
  garantiaContratoJustificativa: '',
  reajusteIndice: '',
  reajusteMeses: '',
  formaEntrega: '',
  entregaParcelas: '',
  entregaPrimeira: '',
  entregaAviso: '',
  prazoValidade: '',
  reajustePeriodo: '',
  dadosOrcamentariosFuncional: '',
  dadosOrcamentariosElemento: '',
  dadosOrcamentariosFonte: '',
  cidade: 'Belém',
  data: '2025-01-01',
  nome: 'Nome do Assinante',
  nomeGuerra: 'Nome Guerra',
  cargo: 'CAP QOBM',
  funcao: 'Chefe'
} as any;

const doc = new jsPDF();
generateTrBensPdf(doc, data);
const out = './tmp_sample_trbens.pdf';
doc.save(out);
console.log('saved', out, 'exists=', existsSync(out), 'size=', existsSync(out) ? statSync(out).size : 'n/a');
